### ISSUE TITLE
Dead link in article

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [cryptostorm/cstorm_deepDNS#3]
The [link to  deepDNS public resolver IPs](https://github.com/cryptostorm/cstorm-deepDNS/blob/master/public_deepdns_resolvers.txt) is 404.

**Comment by df-cryptostorm** [comment]
Link updated with the current resolver list @ https://github.com/cryptostorm/cstorm_deepDNS/blob/master/dnscrypt-resolvers.csv
and removed the paragraph pointing to the now-dead keychain domain, and removed the reference to deepdns.dk (no longer used).
