### ISSUE TITLE
[FIXED] Domain is not resolved 

### ISSUE THREAD

**Issue by sergeevabc** [cryptostorm/cstorm_deepDNS#4]
Dear @df-cryptostorm, could you check why ```x-diesel.com``` is not resolved via ```cs-fi```?
This domain is associated with [Unreal commander][1], a file manager for Windows.

[1]: https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fru.wikipedia.org%2Fwiki%2FUnreal_Commander

**Comment by df-cryptostorm** [comment]
Added *x-diesel.com to the whitelist

**Comment by sergeevabc** [comment]
It is not fully resolved, since that website seems to be dependent on ```x-diesel.org``` and ```x-diesel.biz``` as well which are not resolved at present. What kind of blacklist do you use? For example, a solid one [Notracking][1] does not list aforementioned domains as harmful.

[1]: https://github.com/notracking/hosts-blocklists

**Comment by df-cryptostorm** [comment]
Ah, didn't think those other x-diesel.* domains were related. 
We're using https://github.com/StevenBlack/hosts , the adware + malware file.
Apparently x-diesel*/Unreal commander was once a shareware program, so maybe at one time they were doing some shady things to get people to buy their software. It looks like it's freeware now though, so no more need for that kind of thing.

I think I might switch to that Notracking repo, they look like they'll be less likely to conflict with legitimate services like the StevenBlack one sometimes does.
In the meantime, I'll just add the string "x-diesel" to the whitelist so it'll include any *.x-diesel.* domain.
EDIT:
Done adding to the whitelist. x-diesel.biz/.org/etc. should resolve now.

**Comment by sergeevabc** [comment]
I would not use ```hosts``` by Steven Black.
He’s a [rude fellow][1], who blindly aggregates various half outdated lists.

[1]: https://github.com/StevenBlack/hosts/issues/281

**Comment by df-cryptostorm** [comment]
Wow, that is pretty rude. I was going to switch to Notracking later, but after reading that I think I'll do it right now.
