### ISSUE TITLE
[FIXED] Hardening DNSCrypt

### ISSUE THREAD

**Issue by sergeevabc** [cryptostorm/cstorm_deepDNS#5]
```
dnscrypt-proxy: Generating a new session key pair
dnscrypt-proxy: Done
dnscrypt-proxy: Server certificate with serial '0001' received
dnscrypt-proxy: This certificate is valid
dnscrypt-proxy: Chosen certificate #808****** is valid from [2016-11-03] to [2026-11-01]
dnscrypt-proxy: The key rotation period for this server may exceed the recommended value. This is bad for forward secrecy.
```

Could you make keys rotation happen every 24 hours [at least][3], not every 10 years like it is now?
It seems quite simple to implement according to [this][1] and [that][2] posts.

[1]: https://dnscrypt.pl/2017/01/04/keys-are-now-rotated-every-24-hours/
[2]: https://dnscrypt.pl/2017/02/26/how-key-rotation-is-automated/
[3]: https://dnscrypt.nl/

**Comment by df-cryptostorm** [comment]
Added cronjobs to all the servers that'll rotate the keys every 24 hours.
